server:
  port: 8080
spring:
  datasource:
    #配置驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_guide?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimeZone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    #配置自定义静态资源的位置
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/,file:D:/temp/
  servlet:
    multipart:
      #上传文件的大小配置
      max-file-size: 256MB
      #请求数据大小配置
      max-request-size: 256MB
#上传文件的基本路径
file:
  basePath: D:/temp/

#token的过期时间（单位是毫秒）
token:
  expiration: 36000000

mybatis-plus:
  #配置映射文件
  mapper-locations: classpath:mapper/*Mapper.*xml
  configuration:
    #mybatis输出执行sql、参数和结果集日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #将Java实体类属性的驼峰命名规则转换为数据库字段的下划线命名规则
    map-underscore-to-camel-case: true
    #查询结果中包含空值的列， 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
  #配置别名
  type-aliases-package: com.tjetc.entity